[package]
name = "ratelimit"
version = "0.1.9"
authors = ["Brian Martin <brayniac@gmail.com>"]

license = "MIT"

description = "a token bucket ratelimiter"

homepage = "https://github.com/brayniac/ratelimit"
documentation = "http://brayniac.github.io/ratelimit"
repository = "https://github.com/brayniac/ratelimit"

readme = "README.md"

keywords = [ "ratelimit", "tokenbucket", "rate", "token", "bucket" ]

[dependencies]
time = "*"
shuteye = "*"
