[package]
name = "ratelimit"
version = "0.1.4"
authors = ["Brian Martin <brayniac@gmail.com>"]

license = "MIT"

description = "[work in progress] a token bucket ratelimiter using synchronous channels"

homepage = "https://github.com/brayniac/ratelimit"
documentation = "http://brayniac.github.io/ratelimit"
repository = "https://github.com/brayniac/ratelimit"

readme = "README.md"

keywords = [ "ratelimit", "tokenbucket" ]

[dependencies]
time = "*"
shuteye = "*"
